# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auxilium' do
pod 'BEMAnalogClock'
pod 'MaterialComponents'
pod 'Firebase/Core'
pod 'TesseractOCRiOS', '4.0.0'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Auxilium

  target 'AuxiliumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuxiliumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
